### ISSUE TITLE
WER (%) on LibriCSS

### ISSUE THREAD

**Issue by Chen-jia621** [yangyi0818/DPARNet#2]
你好，我想问一下在libricss上计算wer的时候，我按照Libricss的readme教程跑到
cd exp/data/separation_baseline/utterance/decoding_cmd  
. decode.sh 
这个部分的时候，报错了，发现缺少utterance_separation/utterance_transcription.txt这个文件，然后我从libri_css-master/exp/data/monaural/utterances文件夹下面找到了同名文件，就把它复制过去了，但是在最后计算wer的时候，报错说
Traceback (most recent call last):
File "libri_css-master/external_tools/pykaldi2/example/OpenCSS/local/utt_wer.py", line 35, in
err = editdistance.eval(line, dict_ref[key])
KeyError: 'overlap_ratio_30.0_sil0.1_1.0_session2_actual29.6_utterance_44_0'

请问你有遇到过这个问题吗，怎么解决的呢？

**Comment by yangyi0818** [comment]
你好！建议确认utterance_transcription.txt文件内容是否包含如下文件名：
“overlap_ratio_30.0_sil0.1_1.0_session2_actual29.6_utterance_44_0”
”overlap_ratio_30.0_sil0.1_1.0_session2_actual29.6_utterance_44_1”
以及对应的文本

**Comment by Chen-jia621** [comment]
方便提供一下您用的utterance_transcription.txt文件吗？谢谢！我的邮箱是chenjia@whu.edu.cn

**Comment by yangyi0818** [comment]
对于一条混合语音，如果分离后的语音命名为utterance_X_0.wav 和utterance_X_1.wav （X代表语音序号），utterance_transcription.txt的内容应为：


overlap_ratio_0.0_sil2.9_3.0_session9_actual0.0_utterance_0_0   BUT THEL IS LIKE A FAINT CLOUD KINDLED AT THE RISING SUN I VANISH FROM MY PEARLY THRONE AND WHO SHALL FIND MY PLACE
overlap_ratio_0.0_sil2.9_3.0_session9_actual0.0_utterance_1_0   AND WHY IT SCATTERS ITS BRIGHT BEAUTY THRO THE HUMID AIR
overlap_ratio_0.0_sil2.9_3.0_session9_actual0.0_utterance_2_0   NAY I RATHER THRILLED DISTRUSTING EVERY LIGHT THAT SEEMED TO GILD THE ONWARD PATH AND FEARED TO OVERLEAN A FINGER EVEN
... ...
... ...
... ...
overlap_ratio_0.0_sil2.9_3.0_session9_actual0.0_utterance_0_1   BUT THEL IS LIKE A FAINT CLOUD KINDLED AT THE RISING SUN I VANISH FROM MY PEARLY THRONE AND WHO SHALL FIND MY PLACE
overlap_ratio_0.0_sil2.9_3.0_session9_actual0.0_utterance_1_1   AND WHY IT SCATTERS ITS BRIGHT BEAUTY THRO THE HUMID AIR
overlap_ratio_0.0_sil2.9_3.0_session9_actual0.0_utterance_2_1   NAY I RATHER THRILLED DISTRUSTING EVERY LIGHT THAT SEEMED TO GILD THE ONWARD PATH AND FEARED TO OVERLEAN A FINGER EVEN
... ...
... ...
... ...


如果全部5023条语音用于测试，utterance_transcription.txt应包含10046行。可以自行将此文件整理成上述形式再做尝试。

**Comment by Chen-jia621** [comment]
谢谢！
