### ISSUE TITLE
prepare dataset

### ISSUE THREAD

**Issue by Chen-jia621** [yangyi0818/DPARNet#3]
不好意思又来打扰了，我最近复现了您的这篇文章，在run.sh文件下面有一行 . utils/parse_options.sh文件，我猜这应该是生成rir的脚本文件，由于代码里没有提供，所以我生成了3000个训练的rir，100个测试的rir，然后训练集数目和测试集数目我分别设置的20000和1000，由于不知道您用的什么噪声数据，我训练的时候直接加的高斯白噪声， 然后由于硬件限制，我的batchsize设置的8，学习率设置的0.001，训练到大概60个epoch的时候loss几乎不下降了我就停止训练了，这个时候loss大概在12.5左右。

随后我在libricss进行了测试，但是测试效果并不理想。
0S:9.0
0L:8.9
OV10:11.8
OV20:16.6
OV30:21.23
OV40:23.2

所以想问一下您具体的训练参数是怎么设置的呢？这是我的邮箱2230405092@qq.com，期待您的回复！谢谢！

**Comment by yangyi0818** [comment]
您好！
生成rir的脚本为DPARNet/generate_rir.py 我刚刚对其进行了更新，可以根据此脚本生成训练集rir，在我们的实验中，训练集rir的数量为1w个，参数设置（如房间大小、RT60等）如sms_wsj_replace中配置。
如果训练集的sisdr loss达到-12.5左右，则说明训练过程基本正确。建议根据最新的脚本生成rir再进行训练。

另，请确认在测试libricss时，do_mvdr参数设置为1。同时，建议在仿真测试集上首先进行测试（如sisdr-improvement,pesq，stoi等指标），以防止训练过程出现过拟合。

祝一切顺利！

**Comment by Chen-jia621** [comment]
# Training
use_aneconic=1
channel_permute=1
normalize=0
batch_size=6
num_workers=16
optimizer=adam
lr=0.001
epochs=100

请问这里的use_aneconic=1和normalize=0没有写反吗？我在训练的时候改为了use_aneconic=0和normalize=1 。

**Comment by yangyi0818** [comment]
正如dataset.py中所述，use_aneconic=1表示训练时的目标为aneconic语音，use_aneconic=0表示训练时的目标为reverb语音。建议将use_aneconic设置为1，会获得更好的结果。normalize为测试参数，请保持为0，否则在测试libricss的时候可能会存在问题。

**Comment by Chen-jia621** [comment]
训练时normalize参数需要设置为1吗？

**Comment by yangyi0818** [comment]
请设置为0，训练和测试请保持参数一致

**Comment by Chen-jia621** [comment]
那顺便再问一下DPARnet.py中的SharedLinearAttention可以直接用LinearAttention吗？我安装的fast_transformers中没有SharedLinearAttention，所以改用了LinearAttention，您用的pytorch-fast-transformers是0.4.0版本的吗
