### ISSUE TITLE
where is paper？

### ISSUE THREAD

**Issue by hyysam** [yangyi0818/DPARNet#4]
I cannot find the paper in scholar google

**Comment by yangyi0818** [comment]
Hello!
This paper was accepted two months ago and has not been published yet. The paper in Chinese will be soon uploaded at [https://github.com/yangyi0818/DPARNet](url). The English version is also on the way.

Thanks for your attention to our work!

**Comment by hyysam** [comment]
好的，静待中文版

**Comment by yangyi0818** [comment]
您好，文章已经上传。如果有任何疑问欢迎和我联系。

Please note that this may not be the final version, since it has not been published yet.

**Comment by hyysam** [comment]
ok, thank you!
