### ISSUE TITLE
where is the fast_transformers

### ISSUE THREAD

**Issue by hyysam** [yangyi0818/DPARNet#5]
hello, I can not find：
from fast_transformers.masking import FullMask, LengthMask, TriangularCausalMask
from fast_transformers.attention import SharedLinearAttention, LinearAttention

**Comment by yangyi0818** [comment]
Hello!
You can try installing it from https://pypi.org/project/pytorch-fast-transformers/ or https://github.com/idiap/fast-transformers
The torch version we used is 1.5.0+cu92
